#!/bin/env bash
# set -ex
source ~/.config/malior/envs.sh 2>&1 >/dev/null || true

function help() {
    cat <<EOF
Usage: 
    $(basename $0) [command] <game-application> <args>
    e.g. 
        'malior install xonotic' for start xonotic
        'malior xonotic' for start xonotic
        'malior update' for update malior image
Command:
    help             This usage guide
    update           Update malior image
    recreate         Recreate malior runtime container
    destroy          Stop and remove malior runtime container
    pause            Pause(docker stop) malior runtime container
    resume           Resume(docker start) malior runtime container
    install|update   Install or update game
    remove           Remove game
EOF
}
function install() {
    wget -O - https://github.com/ChisBread/malior/raw/main/docker/$1-install.sh > /tmp/$1-install.sh 
    bash /tmp/$1-install.sh
    rm /tmp/$1-install.sh
}
MALIOR_RUNNING=1
if [ "`sudo docker ps|grep malior-runtime-$USER`" == "" ]; then
    MALIOR_RUNNING=0
fi
DOCKER_OPTS='-i'
if [ -t 0 ] && [ -t 1 ]; then
    DOCKER_OPTS=$DOCKER_OPTS" -t"
fi
#[ ! -d /tmp/.X11-unix ]
function runtime_start() {
    sudo docker run $DOCKER_OPTS -d --restart=no --name=malior-runtime-$USER --privileged=true \
            --cap-add SYS_ADMIN --security-opt seccomp=unconfined --cgroup-parent=docker.slice --cgroupns private \
            --shm-size 512M \
            -e TZ=${TZ:-$(cat /etc/timezone)} -e LANG=${LANG} -e LANGUAGE=${LANGUAGE} -e LC_ALL=${LC_ALL}  \
            -e WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0} \
            -e XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$UID} \
            -e DISPLAY=${DISPLAY:-":0"} \
            -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR:-/run/user/$UID}/pulse/native \
            $(getent group |grep bread | cut -d: -f3|grep -v -P '^(111|121)$'| awk '{print "--group-add "$1}') \
            --mount type=bind,source=/sys/fs/fuse,target=/sys/fs/fuse \
            --mount type=tmpfs,destination=/tmp \
            --mount type=tmpfs,destination=/run \
            --mount type=tmpfs,destination=/run/lock \
            $(ls -v /dev|grep -P 'mali0|dri|udev|snd|shm'|awk '{print "-v /dev/"$1":/dev/"$1}') \
            -v /etc/machine-id:/etc/machine-id \
            -v /etc/pulse:/etc/pulse -v /etc/alsa:/etc/alsa \
            -v /usr/share/alsa:/usr/share/alsa \
            -v ${HOME}/.config/pulse:/home/player/.config/pulse \
            -v /tmp/.X11-unix:/hostfs/tmp/.X11-unix \
            -v ${XDG_RUNTIME_DIR:-/run/user/$UID}:/hostfs${XDG_RUNTIME_DIR:-/run/user/$UID} \
            -v ${HOME}/.config/malior:/home/player/.config/malior \
            -v ${HOME}/.local/malior:/home/player/.local/malior \
            chisbread/rk3588-gaming:${MALIOR_TAG:-base}
    [ "$?" != "0" ] && exit -1
    sleep 1 # TODO wait and check
    sudo docker exec $DOCKER_OPTS --user=root malior-runtime-$USER \
        bash -c \
        "(rm -rf /tmp/.X11-unix || true) \
        && (mkdir -p /run/user || true) && (chmod 755 /run || true) && (chmod 755 /run/user || true) \
        && ln -sf /hostfs/tmp/.X11-unix /tmp/.X11-unix \
        && rm -rf ${XDG_RUNTIME_DIR:-/run/user/$UID} \
        && ln -sf /hostfs${XDG_RUNTIME_DIR:-/run/user/$UID} ${XDG_RUNTIME_DIR:-/run/user/$UID} \
        && chown player:player /home/player/{.config,.local} \
            /home/player/{.config,.local}/malior /home/player/.config/pulse \
        && chmod 0700 ${XDG_RUNTIME_DIR:-/run/user/$UID}"
        
    sudo docker exec $DOCKER_OPTS --user=player malior-runtime-$USER \
        bash -c "ln -sf /home/player/.local/malior/share /home/player/.local/share"

    sudo chown $USER:$USER ${XDG_RUNTIME_DIR:-/run/user/$UID} \
        ${HOME}/{.config,.local} \
        ${HOME}/{.config,.local}/malior \
        ${HOME}/.config/pulse
    sudo chmod 0700 ${XDG_RUNTIME_DIR:-/run/user/$UID}
    sudo chmod 777 /tmp/.X11-unix
}
# process the first parametre only
case $1 in
    help)
        help
        exit
        ;;
    update)
        if [ $MALIOR_RUNNING -eq 1 ]; then
            sudo docker rm -f malior-runtime-$USER
        fi
        sudo docker pull chisbread/rk3588-gaming:${MALIOR_TAG:-base}
        MALIOR_RUNNING=0
        shift
        ;;
    recreate)
        if [ $MALIOR_RUNNING -eq 1 ]; then
            sudo docker rm -f malior-runtime-$USER
        fi
        MALIOR_RUNNING=0
        shift
        ;;
    remove)
        echo 'unimplemented command'
        exit -1
        ;;
    destroy)
        if [ $MALIOR_RUNNING -eq 1 ]; then
            sudo docker rm -f malior-runtime-$USER
        fi
        exit
        ;;
    pause)
        sudo docker stop malior-runtime-$USER
        exit
        ;;
    resume)
        sudo docker start malior-runtime-$USER
        exit
        ;;
    install|update)
        if [ $MALIOR_RUNNING -eq 0 ]; then
            runtime_start
            MALIOR_RUNNING=1
        fi
        install $2
        exit
        ;;
esac
if [ $MALIOR_RUNNING -eq 0 ]; then
    runtime_start
    exit
fi
sudo docker exec $DOCKER_OPTS --user=${MALIOR_EXEC_USER:-player} malior-runtime-$USER bash -c "source /home/player/.config/malior/envs.sh ; $*"